---
name: Release Griffin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install packages
      run: HOMEBREW_NO_INSTALL_CLEANUP=1 brew install goreleaser/tap/goreleaser

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21

    - name: Test Griffin
      run: make test

    - name: Semantic Release
      uses: go-semantic-release/action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        [[ -f .generated-go-semantic-release-changelog.md ]] && git add .generated-go-semantic-release-changelog.md 
        [[ -d .semrel/ ]] && git add .semrel/
        git diff --quiet && git diff --staged --quiet || (git commit -m 'Update generated files' && git push)        

    # - name: Semantic Release
    #   uses: cycjimmy/semantic-release-action@v4
    #   with:
    #       branches: |
    #         [
    #           "main"
    #         ]
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release Griffin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make release
