---
name: Test Griffin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install packages
      run: HOMEBREW_NO_INSTALL_CLEANUP=1 brew install goreleaser/tap/goreleaser

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21

    - name: Test Griffin
      run: make test
